config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "users#index"

  get "group/home", to:"group#home"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :name

  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def home
    @groups = GroupGenerator.new(all_users).generate unless all_users.empty?
  end

  private

  def all_users
    User.all
  end

  class GroupGenerator
    attr_accessor :list

    def initialize(list)
      @list = list
    end

    def generate
      groups = list.shuffle.each_slice(3).to_a
      extras = groups.select { |group| group.size < 3 }
      groups = groups - extras
      extras.each do |extra_group|
        extra_group.each { |user| groups.sample << user }
        extras.delete(extra_group)
      end
      groups
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'New User has been created'
      redirect_to users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = 'User has been Deleted!'

    redirect_to '/'
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/group/_new.html.haml
- if @groups.present?
  - @groups.each_with_index do |group, i|
    %ul
      %li= "Lunch Group #{i+1} (with #{group.size} People)"
      - group.each do |user|
        %ul
          - binding.pry if user.class == Array
          %li= user.name
        %p

- else
  %h4 No Users to generate groups

app/views/group/home.html.haml
%h2 Lunch Groups

-# = link_to 'Generate', generate_groups_group_index_path(@groups)

= render 'group/new'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Group
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -# # ==== Removing/Adding back
    %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Groups Home", group_home_path
          %li= link_to "Users Page",  users_path
          %li= link_to "Create New User",  new_user_path
    -# # /==== Removing/Adding back
    = yield
    %p
    = notice

app/views/users/index.html.haml
%p
= link_to "Add New User", new_user_path

%h2 Current Users
- if @users.any?

  - @users.each do |user|
    %ul
      %li= link_to user.try(:name), user_path(user)

- else
  %h1 Nothing here!!

app/views/users/new.html.haml
= form_for @user do |f|

  = f.text_field :first_name

  = f.text_field :last_name

  = f.submit

app/views/users/show.html.haml
%p= @user.first_name

%p= @user.last_name

%h2 Or do you want to delete this User?
= link_to "Delete #{@user.name}", user_path(@user), method: :delete